(function(root){
'use strict';
function neighbors(i){var a=[];if(i%6)a.push(i-1);if(i%6<5)a.push(i+1);if(i>=6)a.push(i-6);if(i<24)a.push(i+6);return a;}
var adj=[];for(var ai=0;ai<30;ai++)adj.push(neighbors(ai));
function matches(input){var b=input.slice(),total=0,first=0,wave=0;while(true){var mark=[],i,j,k,t,n=0;for(i=0;i<30;i++){if(b[i]===6)continue;if(i%6<4&&b[i]===b[i+1]&&b[i]===b[i+2])mark[i]=mark[i+1]=mark[i+2]=true;if(i<18&&b[i]===b[i+6]&&b[i]===b[i+12])mark[i]=mark[i+6]=mark[i+12]=true;}var seen=[];for(i=0;i<30;i++){if(!mark[i]||seen[i])continue;n++;var q=[i];seen[i]=true;while(q.length){j=q.pop();for(k=0;k<adj[j].length;k++){t=adj[j][k];if(mark[t]&&!seen[t]&&b[t]===b[j]){seen[t]=true;q.push(t);}}}}if(!n)break;if(!wave)first=n;total+=n;wave++;for(i=0;i<30;i++)if(mark[i])b[i]=6;for(i=0;i<6;i++){var v=[];for(j=24+i;j>=0;j-=6)if(b[j]!==6)v.push(b[j]);for(j=24+i,k=0;j>=0;j-=6,k++)b[j]=k<v.length?v[k]:6;}}return {total:total,first:first};}
function potential(b){var p=0;for(var i=0;i<30;i++){if(i%6<5&&b[i]===b[i+1])p++;if(i<24&&b[i]===b[i+6])p++;}return p;}
function solve(b,mode){if(b.length!==30||b.some(function(x){return x<0||x>7||x===6;}))throw Error('请补全全部珠子');var easy=mode!=='combo',limit=15,width=easy?100:200,budget=easy?1400:3500,start=Date.now(),layer=[],best=null,counts=[],upper=0;for(var i=0;i<30;i++){counts[b[i]]=(counts[b[i]]||0)+1;layer.push({b:b.slice(),path:[i]});}for(i=0;i<8;i++)upper+=Math.floor((counts[i]||0)/3);for(var d=0;d<limit;d++){var next=[],used=Object.create(null);for(var z=0;z<layer.length;z++){var node=layer[z],last=node.path[node.path.length-1];for(var a=0;a<adj[last].length;a++){var to=adj[last][a];if(node.path.length>1&&to===node.path[node.path.length-2])continue;var nb=node.b.slice(),tmp=nb[last];nb[last]=nb[to];nb[to]=tmp;var key=nb.join('')+':'+to;if(used[key])continue;used[key]=1;var m=matches(nb),path=node.path.concat(to),candidate={b:nb,path:path,total:m.total,first:m.first,rank:m.total*1000+m.first*30+potential(nb)};if(m.total>0&&(!best||m.total>best.total||(m.total===best.total&&path.length<best.path.length)))best=candidate;if(best&&best.total>=upper)return best;next.push(candidate);if(Date.now()-start>budget)return best;}}next.sort(function(x,y){return y.rank-x.rank;});layer=next.slice(0,width);if(!layer.length)break;}return best;}
function rgb(frame,x,y){x=Math.max(0,Math.min(frame.width-1,x|0));y=Math.max(0,Math.min(frame.height-1,y|0));var k=(y*frame.width+x)*4;return [frame.data[k],frame.data[k+1],frame.data[k+2]];}
function color(p){var r=p[0]/255,g=p[1]/255,b=p[2]/255,max=Math.max(r,g,b),min=Math.min(r,g,b),dif=max-min;if(max<.25||dif/max<.38)return 6;var h=max===r?((g-b)/dif)%6:max===g?(b-r)/dif+2:(r-g)/dif+4;h=(h*60+360)%360;return h<32||h>=348?0:h<72?3:h<169?2:h<246?1:h<293?4:5;}
function patch(frame,cx,cy,size){var out=[];for(var y=-4;y<=4;y++)for(var x=-4;x<=4;x++){if(x>1&&y>1)continue;var p=rgb(frame,cx+x*size*.08,cy+y*size*.08);out.push((p[0]<<16)|(p[1]<<8)|p[2]);}return out;}
function distance(a,b){var sum=0;for(var i=0;i<a.length;i++){sum+=Math.abs((a[i]>>16&255)-(b[i]>>16&255))+Math.abs((a[i]>>8&255)-(b[i]>>8&255))+Math.abs((a[i]&255)-(b[i]&255));}return sum/(a.length*3);}
function cell(frame,cx,cy,size,templates){var p=patch(frame,cx,cy,size),center=rgb(frame,cx,cy),bestCross=255,votes=[0,0,0,0,0,0],samples=0,lo=255,hi=0;for(var t=0;t<templates.length;t++)if(templates[t].type===7)bestCross=Math.min(bestCross,distance(p,templates[t].pixels));if(Math.max.apply(null,center)<140&&bestCross<=22)return {type:7,error:bestCross};for(var y=-4;y<=4;y++)for(var x=-4;x<=4;x++){var r=x*x+y*y;if(r<4||r>16||(x>1&&y>1))continue;var q=rgb(frame,Math.round(cx+x*size*.065),Math.round(cy+y*size*.065)),v=color(q),bright=Math.max.apply(null,q);lo=Math.min(lo,bright);hi=Math.max(hi,bright);samples++;if(v<6)votes[v]++;}var order=[0,1,2,3,4,5].sort(function(a,b){return votes[b]-votes[a];}),type=order[0],err=255;if(hi-lo<45||votes[type]<samples*.4||votes[type]-votes[order[1]]<samples*.15)return {type:6,error:255};for(t=0;t<templates.length;t++)if(templates[t].type===type)err=Math.min(err,distance(p,templates[t].pixels));return {type:type,error:err};}
function read(frame,rect,templates,early){var b=[],errors=[],fail=0,score=0;for(var i=0;i<30;i++){var v=cell(frame,rect.x+(i%6+.5)*rect.s,rect.y+(Math.floor(i/6)+.5)*rect.s,rect.s,templates);b.push(v.type);errors.push(v.error);score+=v.error;if(v.error>35)fail++;if(early&&fail>3)return null;}return {board:b,errors:errors,fail:fail,rect:rect,score:fail*256+score/30};}
function recognize(frame,templates){var best=null,stride=Math.max(3,Math.floor(frame.width/160)),start=Date.now();for(var scale=100;scale>=60;scale-=2){var size=frame.width*scale/600,remain=frame.width-size*6;for(var offset=0;offset<(remain<1?1:3);offset++){var left=remain*offset/2;for(var top=Math.floor(frame.height*.25);top<=frame.height-size*5;top+=stride){var r=read(frame,{x:left,y:top,s:size},templates,true);if(!r)continue;if(!best||r.score<best.score)best=r;if(!r.fail)return r;for(var d=1;d<stride;d++)for(var sign=-1;sign<=1;sign+=2){var rt=top+d*sign;if(rt<0||rt+size*5>frame.height)continue;var fine=read(frame,{x:left,y:rt,s:size},templates,true);if(fine&&(!best||fine.score<best.score))best=fine;if(fine&&!fine.fail)return fine;}if(Date.now()-start>6500)return best;}}if(Date.now()-start>6500)break;}return best;}
root.OrbCore={solve:solve,matches:matches,recognize:recognize,read:read,neighbors:neighbors};
})(typeof self!=='undefined'?self:globalThis);
